/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aula18.ex1;

/**
 *
 * @author Rafael
 */
public class Radios extends javax.swing.JFrame {

    /** Creates new form Radios */
    public Radios() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFonte = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tfEstilo = new javax.swing.JTextField();
        cbNormal = new javax.swing.JRadioButton();
        cbNegrito = new javax.swing.JRadioButton();
        cbItalico = new javax.swing.JRadioButton();
        cbNegritoItalico = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teste de Rádio");
        setPreferredSize(new java.awt.Dimension(800, 600));

        tfEstilo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfEstilo.setText("Escolha o estilo");
        tfEstilo.setName("tfFonte"); // NOI18N

        bgFonte.add(cbNormal);
        cbNormal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbNormal.setText("Normal");
        cbNormal.setName("rbNormal"); // NOI18N

        bgFonte.add(cbNegrito);
        cbNegrito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbNegrito.setText("Negrito");
        cbNegrito.setName("rbNegrito"); // NOI18N

        bgFonte.add(cbItalico);
        cbItalico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbItalico.setText("Itálico");
        cbItalico.setName("rbItalico"); // NOI18N

        bgFonte.add(cbNegritoItalico);
        cbNegritoItalico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbNegritoItalico.setText("Negrito e Itálico");
        cbNegritoItalico.setName("rbNegritoItalico"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbNegrito)
                        .addGap(56, 56, 56)
                        .addComponent(cbItalico)
                        .addGap(42, 42, 42)
                        .addComponent(cbNegritoItalico))
                    .addComponent(tfEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tfEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNormal)
                    .addComponent(cbNegrito)
                    .addComponent(cbItalico)
                    .addComponent(cbNegritoItalico))
                .addContainerGap(398, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Radios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Radios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Radios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Radios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Radios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFonte;
    private javax.swing.JRadioButton cbItalico;
    private javax.swing.JRadioButton cbNegrito;
    private javax.swing.JRadioButton cbNegritoItalico;
    private javax.swing.JRadioButton cbNormal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfEstilo;
    // End of variables declaration//GEN-END:variables

}
