/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula24.ex3;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class Biblioteca extends javax.swing.JFrame {

    ArrayList<Livro> livros = new ArrayList<Livro>();
    
    /**
     * Creates new form Biblioteca
     */
    public Biblioteca() {
        initComponents();
    }
    
    public void criarLivros() {
        Livro livro1 = new Livro();
        Livro livro2 = new Livro();
        Livro livro3 = new Livro();
        livro1.setTitulo("Sherlock Holmes 3");
        livro1.setAutor("Arthur Conan Doyle");
        livro1.setAnoPublicacao(1889);
        livro2.setDisponibilidade(true);
        livro1.setNumeroPaginas(550);
        livro1.setEditora("Abril");
        livros.add(livro1);
        livro2.setTitulo("Senhor dos Anéis 1");
        livro2.setAutor("JRR Tolkien");
        livro2.setAnoPublicacao(1900);
        livro2.setDisponibilidade(false);
        livro2.setNumeroPaginas(800);
        livro2.setEditora("Verbo");
        livros.add(livro2);
        livro3.setTitulo("Jogos Vorazes 2");
        livro3.setAutor("Suzane Collins");
        livro3.setAnoPublicacao(2009);
        livro3.setDisponibilidade(true);
        livro3.setNumeroPaginas(660);
        livro3.setEditora("Leya");
        livros.add(livro3);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLivros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbLivros = new javax.swing.JComboBox<>();
        pnBotoes = new javax.swing.JPanel();
        btDisponibilidade = new javax.swing.JButton();
        btEmprestimo = new javax.swing.JButton();
        btDevolucao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca do Java");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Biblioteca do Java");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setText("Livro:");

        cbLivros.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnLivrosLayout = new javax.swing.GroupLayout(pnLivros);
        pnLivros.setLayout(pnLivrosLayout);
        pnLivrosLayout.setHorizontalGroup(
            pnLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLivrosLayout.createSequentialGroup()
                .addGroup(pnLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLivrosLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1))
                    .addGroup(pnLivrosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnLivrosLayout.setVerticalGroup(
            pnLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLivrosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(pnLivros);

        btDisponibilidade.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btDisponibilidade.setText("Disponível?");
        btDisponibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDisponibilidadeActionPerformed(evt);
            }
        });
        pnBotoes.add(btDisponibilidade);

        btEmprestimo.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btEmprestimo.setText("Emprestar");
        btEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmprestimoActionPerformed(evt);
            }
        });
        pnBotoes.add(btEmprestimo);

        btDevolucao.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btDevolucao.setText("Devolver");
        btDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDevolucaoActionPerformed(evt);
            }
        });
        pnBotoes.add(btDevolucao);

        getContentPane().add(pnBotoes);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        criarLivros();
        for (int i = 0; i < livros.size(); i++)
            cbLivros.addItem(livros.get(i).getTitulo());
    }//GEN-LAST:event_formWindowOpened

    private void btDisponibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDisponibilidadeActionPerformed
        Livro livro = new Livro();
        livro = livros.get(cbLivros.getSelectedIndex());
        
        JOptionPane.showMessageDialog(this, livro.verificarDisponibilidade());
    }//GEN-LAST:event_btDisponibilidadeActionPerformed

    private void btEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmprestimoActionPerformed
        Livro livro = new Livro();
        livro = livros.get(cbLivros.getSelectedIndex());
                
        if (livro.emprestar() == true) {
            JOptionPane.showMessageDialog(this, "Empréstimo realizado com sucesso!");
        }
        else {
            JOptionPane.showMessageDialog(this, "Livro indisponível para Empréstimo!");
        }
    }//GEN-LAST:event_btEmprestimoActionPerformed

    private void btDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDevolucaoActionPerformed
        Livro livro = new Livro();
        livro = livros.get(cbLivros.getSelectedIndex());
        
        livro.devolver();
    }//GEN-LAST:event_btDevolucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDevolucao;
    private javax.swing.JButton btDisponibilidade;
    private javax.swing.JButton btEmprestimo;
    private javax.swing.JComboBox<String> cbLivros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JPanel pnLivros;
    // End of variables declaration//GEN-END:variables
}
