/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula24.ex2;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class Banco extends javax.swing.JFrame {

    ArrayList<Conta> contas = new ArrayList<Conta>();
    
    /**
     * Creates new form Banco
     */
    public Banco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOperacao = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNumeroConta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNomeTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfCpfTitular = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cbContas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tfTitular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbSacar = new javax.swing.JRadioButton();
        rbDepositar = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        btRealizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco do Java");
        setMinimumSize(new java.awt.Dimension(220, 430));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Banco do Java");
        getContentPane().add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Número da Conta:");
        getContentPane().add(jLabel2);

        tfNumeroConta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(tfNumeroConta);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nome do Titular:");
        getContentPane().add(jLabel3);

        tfNomeTitular.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(tfNomeTitular);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("CPF do Titular:");
        getContentPane().add(jLabel4);

        tfCpfTitular.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(tfCpfTitular);

        btCadastrar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btCadastrar.setText("Cadastrar Conta");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrar);
        getContentPane().add(jSeparator1);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Contas:");
        getContentPane().add(jLabel6);

        cbContas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbContas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbContasItemStateChanged(evt);
            }
        });
        getContentPane().add(cbContas);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Titular:");
        getContentPane().add(jLabel8);

        tfTitular.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tfTitular.setEnabled(false);
        getContentPane().add(tfTitular);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Saldo:");
        getContentPane().add(jLabel10);

        tfSaldo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tfSaldo.setEnabled(false);
        getContentPane().add(tfSaldo);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Operações:");
        getContentPane().add(jLabel5);

        bgOperacao.add(rbSacar);
        rbSacar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbSacar.setText("Sacar");
        getContentPane().add(rbSacar);

        bgOperacao.add(rbDepositar);
        rbDepositar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbDepositar.setText("Depositar");
        getContentPane().add(rbDepositar);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Valor:");
        getContentPane().add(jLabel7);

        tfValor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(tfValor);

        btRealizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btRealizar.setText("Realizar Operação");
        btRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealizarActionPerformed(evt);
            }
        });
        getContentPane().add(btRealizar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Pessoa titular = new Pessoa();
        titular.setNome(tfNomeTitular.getText());
        titular.setCpf(Long.parseLong(tfCpfTitular.getText()));
        
        Conta conta = new Conta();
        conta.setNumero(Integer.parseInt(tfNumeroConta.getText()));
        conta.setTitular(titular);
        conta.setSaldo(0);
        
        contas.add(conta);
        cbContas.addItem(String.valueOf(conta.getNumero()));
        
        tfNumeroConta.setText("");
        tfNomeTitular.setText("");
        tfCpfTitular.setText("");
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealizarActionPerformed
        Conta conta;
        int indice;
        indice = cbContas.getSelectedIndex();
        
        conta = contas.get(indice);
        
        if (rbDepositar.isSelected()) {
            conta.depositar(Float.parseFloat(tfValor.getText()));
            JOptionPane.showMessageDialog(this, "Depósito realizado com sucesso!");
        } 
        else if (rbSacar.isSelected()) {
            if (conta.sacar(Float.parseFloat(tfValor.getText())) == true) {
                JOptionPane.showMessageDialog(this, "Saque realizado com sucesso!");
            }
            else {
                JOptionPane.showMessageDialog(this, "Não há saldo suficiente para sacar!");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Nenhuma operação foi selecionada!");
        }
        atualizar();
    }//GEN-LAST:event_btRealizarActionPerformed

    private void atualizar() {
        Conta conta;
        conta = contas.get(cbContas.getSelectedIndex());
        tfTitular.setText(conta.getTitular().getNome());
        tfSaldo.setText(String.valueOf(conta.getSaldo()));
    }
    
    private void cbContasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbContasItemStateChanged
        atualizar();
    }//GEN-LAST:event_cbContasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOperacao;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btRealizar;
    private javax.swing.JComboBox<String> cbContas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbDepositar;
    private javax.swing.JRadioButton rbSacar;
    private javax.swing.JTextField tfCpfTitular;
    private javax.swing.JTextField tfNomeTitular;
    private javax.swing.JTextField tfNumeroConta;
    private javax.swing.JTextField tfSaldo;
    private javax.swing.JTextField tfTitular;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
