/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula22.exemplo2;

import aula21.exemplo.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Rafael
 */
public abstract class FormTemplate extends javax.swing.JFrame {

    /**
     * Creates new form FormTemplate
     */
    public FormTemplate() {
        initComponents();
        btConsultar.addActionListener((ActionListener) this);
        btInserir.addActionListener((ActionListener) this);
    }

    public abstract void btConsultarActionPerformed (ActionEvent e);
    public abstract void btInserirActionPerformed (ActionEvent e);
    
    public void actionPerformed (ActionEvent e) {
       
        switch (e.getActionCommand()) {
            
            case "Consultar":
                btConsultarActionPerformed(e);
                break;
            case "Inserir":
                btInserirActionPerformed(e);
                break;
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNorte = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        btConsultar = new javax.swing.JButton();
        pnSul = new javax.swing.JPanel();
        spSul = new javax.swing.JSeparator();
        btInserir = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulário Template");
        setPreferredSize(new java.awt.Dimension(500, 400));

        lbCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCodigo.setText("Código:");

        tfCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btConsultar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btConsultar.setText("Consultar");

        javax.swing.GroupLayout pnNorteLayout = new javax.swing.GroupLayout(pnNorte);
        pnNorte.setLayout(pnNorteLayout);
        pnNorteLayout.setHorizontalGroup(
            pnNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNorteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnNorteLayout.setVerticalGroup(
            pnNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNorteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(pnNorte, java.awt.BorderLayout.NORTH);

        btInserir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btInserir.setText("Inserir");

        btExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btExcluir.setText("Excluir");

        btCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btCancelar.setText("Cancelar");

        javax.swing.GroupLayout pnSulLayout = new javax.swing.GroupLayout(pnSul);
        pnSul.setLayout(pnSulLayout);
        pnSulLayout.setHorizontalGroup(
            pnSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSulLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(spSul, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCancelar)
                .addGap(89, 89, 89))
        );
        pnSulLayout.setVerticalGroup(
            pnSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spSul, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btInserir)
                    .addComponent(btExcluir))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(pnSul, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btCancelar;
    protected javax.swing.JButton btConsultar;
    protected javax.swing.JButton btExcluir;
    protected javax.swing.JButton btInserir;
    protected javax.swing.JLabel lbCodigo;
    private javax.swing.JPanel pnNorte;
    private javax.swing.JPanel pnSul;
    protected javax.swing.JSeparator spSul;
    protected javax.swing.JTextField tfCodigo;
    // End of variables declaration//GEN-END:variables
}
