/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula20.ex1;

import aula18.ex2.*;

/**
 *
 * @author Rafael
 */
public class Calculadora extends javax.swing.JFrame {

    private int n1, n2;
    private char operacao;
    
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tfResultado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tf7 = new javax.swing.JButton();
        tf8 = new javax.swing.JButton();
        tf9 = new javax.swing.JButton();
        tfDivide = new javax.swing.JButton();
        tf4 = new javax.swing.JButton();
        tf5 = new javax.swing.JButton();
        tf6 = new javax.swing.JButton();
        tfMultiplica = new javax.swing.JButton();
        tf1 = new javax.swing.JButton();
        tf2 = new javax.swing.JButton();
        tf3 = new javax.swing.JButton();
        tfSubtrai = new javax.swing.JButton();
        tf0 = new javax.swing.JButton();
        tfLimpa = new javax.swing.JButton();
        tfIgual = new javax.swing.JButton();
        tfSoma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Básica");
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(600, 200));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        tfResultado.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfResultado.setEnabled(false);
        tfResultado.setPreferredSize(new java.awt.Dimension(600, 40));
        jPanel2.add(tfResultado);

        getContentPane().add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel1.setName("teste"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        tf7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tf7.setForeground(new java.awt.Color(0, 153, 255));
        tf7.setText("7");
        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        jPanel1.add(tf7);

        tf8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tf8.setForeground(new java.awt.Color(0, 153, 255));
        tf8.setText("8");
        tf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf8ActionPerformed(evt);
            }
        });
        jPanel1.add(tf8);

        tf9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tf9.setForeground(new java.awt.Color(0, 153, 255));
        tf9.setText("9");
        tf9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf9ActionPerformed(evt);
            }
        });
        jPanel1.add(tf9);

        tfDivide.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfDivide.setForeground(new java.awt.Color(255, 102, 102));
        tfDivide.setText("/");
        tfDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDivideActionPerformed(evt);
            }
        });
        jPanel1.add(tfDivide);

        tf4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tf4.setForeground(new java.awt.Color(0, 153, 255));
        tf4.setText("4");
        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        jPanel1.add(tf4);

        tf5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tf5.setForeground(new java.awt.Color(0, 153, 255));
        tf5.setText("5");
        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });
        jPanel1.add(tf5);

        tf6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tf6.setForeground(new java.awt.Color(0, 153, 255));
        tf6.setText("6");
        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });
        jPanel1.add(tf6);

        tfMultiplica.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfMultiplica.setForeground(new java.awt.Color(255, 102, 102));
        tfMultiplica.setText("*");
        tfMultiplica.setName(""); // NOI18N
        tfMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMultiplicaActionPerformed(evt);
            }
        });
        jPanel1.add(tfMultiplica);

        tf1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tf1.setForeground(new java.awt.Color(0, 153, 255));
        tf1.setText("1");
        tf1.setToolTipText("");
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel1.add(tf1);

        tf2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tf2.setForeground(new java.awt.Color(0, 153, 255));
        tf2.setText("2");
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        jPanel1.add(tf2);

        tf3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tf3.setForeground(new java.awt.Color(0, 153, 255));
        tf3.setText("3");
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        jPanel1.add(tf3);

        tfSubtrai.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfSubtrai.setForeground(new java.awt.Color(255, 102, 102));
        tfSubtrai.setText("-");
        tfSubtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSubtraiActionPerformed(evt);
            }
        });
        jPanel1.add(tfSubtrai);

        tf0.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tf0.setForeground(new java.awt.Color(0, 153, 255));
        tf0.setText("0");
        tf0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf0ActionPerformed(evt);
            }
        });
        jPanel1.add(tf0);

        tfLimpa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfLimpa.setForeground(new java.awt.Color(255, 51, 51));
        tfLimpa.setText("C");
        tfLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLimpaActionPerformed(evt);
            }
        });
        jPanel1.add(tfLimpa);

        tfIgual.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfIgual.setForeground(new java.awt.Color(0, 204, 102));
        tfIgual.setText("=");
        tfIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIgualActionPerformed(evt);
            }
        });
        jPanel1.add(tfIgual);

        tfSoma.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfSoma.setForeground(new java.awt.Color(255, 102, 102));
        tfSoma.setText("+");
        tfSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSomaActionPerformed(evt);
            }
        });
        jPanel1.add(tfSoma);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf0ActionPerformed
        tfResultado.setText(tfResultado.getText() + "0");
    }//GEN-LAST:event_tf0ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        tfResultado.setText(tfResultado.getText() + "1");
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        tfResultado.setText(tfResultado.getText() + "2");
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        tfResultado.setText(tfResultado.getText() + "3");
    }//GEN-LAST:event_tf3ActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        tfResultado.setText(tfResultado.getText() + "4");
    }//GEN-LAST:event_tf4ActionPerformed

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
        tfResultado.setText(tfResultado.getText() + "5");
    }//GEN-LAST:event_tf5ActionPerformed

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
        tfResultado.setText(tfResultado.getText() + "6");
    }//GEN-LAST:event_tf6ActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        tfResultado.setText(tfResultado.getText() + "7");
    }//GEN-LAST:event_tf7ActionPerformed

    private void tf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf8ActionPerformed
        tfResultado.setText(tfResultado.getText() + "8");
    }//GEN-LAST:event_tf8ActionPerformed

    private void tf9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf9ActionPerformed
        tfResultado.setText(tfResultado.getText() + "9");
    }//GEN-LAST:event_tf9ActionPerformed

    private void tfLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLimpaActionPerformed
        limpar();
    }//GEN-LAST:event_tfLimpaActionPerformed

    private void tfSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSomaActionPerformed
        this.operacao = '+';
        this.n1 = Integer.parseInt(tfResultado.getText());
        limpar();
    }//GEN-LAST:event_tfSomaActionPerformed

    private void tfSubtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSubtraiActionPerformed
        this.operacao = '-';
        this.n1 = Integer.parseInt(tfResultado.getText());
        limpar();
    }//GEN-LAST:event_tfSubtraiActionPerformed

    private void tfMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMultiplicaActionPerformed
        this.operacao = '*';
        this.n1 = Integer.parseInt(tfResultado.getText());
        limpar();
    }//GEN-LAST:event_tfMultiplicaActionPerformed

    private void tfDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDivideActionPerformed
        this.operacao = '/';
        this.n1 = Integer.parseInt(tfResultado.getText());
        limpar();
    }//GEN-LAST:event_tfDivideActionPerformed

    private void tfIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIgualActionPerformed
        this.n2 = Integer.parseInt(tfResultado.getText());
        calcular();
    }//GEN-LAST:event_tfIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton tf0;
    private javax.swing.JButton tf1;
    private javax.swing.JButton tf2;
    private javax.swing.JButton tf3;
    private javax.swing.JButton tf4;
    private javax.swing.JButton tf5;
    private javax.swing.JButton tf6;
    private javax.swing.JButton tf7;
    private javax.swing.JButton tf8;
    private javax.swing.JButton tf9;
    private javax.swing.JButton tfDivide;
    private javax.swing.JButton tfIgual;
    private javax.swing.JButton tfLimpa;
    private javax.swing.JButton tfMultiplica;
    private javax.swing.JTextField tfResultado;
    private javax.swing.JButton tfSoma;
    private javax.swing.JButton tfSubtrai;
    // End of variables declaration//GEN-END:variables

    private void calcular() {
        int resultado = 0;
        
        switch (this.operacao) {
            case '+' :
                resultado = this.n1 + this.n2;
                break;
            case '-':
                resultado = this.n1 - this.n2;
                break;
            case '/':
                resultado = this.n1 / this.n2;
                break;
            case '*':
                resultado = this.n1 * this.n2;
                break;
            default:
                break;
        }
        tfResultado.setText(String.valueOf(resultado));
    }

    private void limpar() {
        tfResultado.setText("");
    }
}
