/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula23.ex123;

import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class Caixas extends javax.swing.JFrame {

    /**
     * Creates new form Caixas
     */
    public Caixas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        btInfo = new javax.swing.JButton();
        btAdv = new javax.swing.JButton();
        btErro = new javax.swing.JButton();
        btQuest = new javax.swing.JButton();
        btMens = new javax.swing.JButton();
        btCalcular = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplos de MessageDialog");

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitulo.setText("Caixas de Diálogo");

        btInfo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btInfo.setText("Informação");
        btInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInfoActionPerformed(evt);
            }
        });

        btAdv.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btAdv.setText("Advertência");
        btAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdvActionPerformed(evt);
            }
        });

        btErro.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btErro.setText("Erro");
        btErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btErroActionPerformed(evt);
            }
        });

        btQuest.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btQuest.setText("Questionamento");
        btQuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuestActionPerformed(evt);
            }
        });

        btMens.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btMens.setText("Mensagem");
        btMens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMensActionPerformed(evt);
            }
        });

        btCalcular.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btErro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQuest)
                            .addComponent(btMens, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbTitulo)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btInfo)
                .addGap(18, 18, 18)
                .addComponent(btAdv)
                .addGap(18, 18, 18)
                .addComponent(btErro)
                .addGap(18, 18, 18)
                .addComponent(btQuest)
                .addGap(18, 18, 18)
                .addComponent(btMens)
                .addGap(18, 18, 18)
                .addComponent(btCalcular)
                .addGap(18, 18, 18)
                .addComponent(btExcluir)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInfoActionPerformed
        JOptionPane.showMessageDialog(null, "Mensagem de informação.",
                "Informação", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btInfoActionPerformed

    private void btAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdvActionPerformed
        JOptionPane.showMessageDialog(null, "Mensagem de Advertência!", 
                "Advertência", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btAdvActionPerformed

    private void btErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btErroActionPerformed
        JOptionPane.showMessageDialog(null, "Mensagem de Erro!", 
                "Erro", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btErroActionPerformed

    private void btQuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuestActionPerformed
        JOptionPane.showMessageDialog(null, "Mensagem de Questionamento.", 
                "Questionamento", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_btQuestActionPerformed

    private void btMensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMensActionPerformed
        JOptionPane.showMessageDialog(this, "Mensagem Simples.", 
                "Simples", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btMensActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        String valor;
        double n1, n2, res;
        valor = JOptionPane.showInputDialog(null, "Digite o primeiro número:");
        n1 = Double.parseDouble(valor);
        valor = JOptionPane.showInputDialog(null, "Digite o segundo número:");
        n2 = Double.parseDouble(valor);
        res = n1 + n2;
        JOptionPane.showMessageDialog(null, "O resultado da soma é: " + res);
        res = n1 - n2;
        JOptionPane.showMessageDialog(null, "O resultado da subtração é: " + res);
        res = n1 * n2;
        JOptionPane.showMessageDialog(null, "O resultado da multiplicação é: " + res);
        res = n1 / n2;
        JOptionPane.showMessageDialog(this, "O resultado da divisão é: " + res);    
    }//GEN-LAST:event_btCalcularActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int retorno;
        retorno = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o arquivo?",
                "Confirmação de exclusão", JOptionPane.YES_NO_CANCEL_OPTION);
        if (retorno == 0) {
            JOptionPane.showMessageDialog(this, "Arquivo excluído com sucesso!");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdv;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btErro;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInfo;
    private javax.swing.JButton btMens;
    private javax.swing.JButton btQuest;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
