/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula22.exemplo1;

/**
 *
 * @author Rafael
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTela2 = new javax.swing.JButton();
        btTela3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.FlowLayout());

        btTela2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btTela2.setText("Abrir Tela 2");
        btTela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTela2ActionPerformed(evt);
            }
        });
        getContentPane().add(btTela2);

        btTela3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btTela3.setText("Abrir Tela 3");
        btTela3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTela3ActionPerformed(evt);
            }
        });
        getContentPane().add(btTela3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTela2ActionPerformed

        TelaSecundaria t2 = new TelaSecundaria();
        
        t2.frTelaP = this;
        
        t2.setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btTela2ActionPerformed

    private void btTela3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTela3ActionPerformed
        
        TelaTerciaria t3 = new TelaTerciaria();
        
        t3.frTelaP = this;
        
        t3.setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btTela3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTela2;
    private javax.swing.JButton btTela3;
    // End of variables declaration//GEN-END:variables
}
